version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg17
    container_name: trawl_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trawl_db
    ports:
      - "7000:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - trawl_net

  redis:
    image: redis:7-alpine
    container_name: trawl_redis
    restart: always
    networks:
      - trawl_net

  searxng:
    image: searxng/searxng:latest
    container_name: trawl_searxng
    restart: always
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080
    ports:
      - "8888:8080"
    volumes:
      - ./searxng:/etc/searxng:ro
    depends_on:
      - redis
    networks:
      - trawl_net

  backend:
    build: .
    container_name: trawl_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/trawl_db
      - SEARXNG_BASE_URL=http://searxng:8080
      - API_BASE=http://localhost:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - searxng
    networks:
      - trawl_net

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: trawl_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "7001:80"
    depends_on:
      - db
    networks:
      - trawl_net

networks:
  trawl_net:
    driver: bridge

volumes:
  db_data:
